### ISSUE TITLE
Nextcloud kann MariaDB nicht erreichen

### ISSUE THREAD

**Issue by MarkusLoyen** [cbirkenbeul/docker-homelab#11]
Hallo zusammen,

ersteinmal danke an Christian, für die tollen Videos und dieses Repository.
Habe ein Problem mit der Nextcloud, die die MariaDB nicht erreichen kann.
Voraussetzungen:
Debian 10.2.0 in einer VM frisch installiert, sowie
Docker und docker-compose und ein paar Tools, die ich gern nutze.
das Repository gecloned und die Anpassungen durchgeführt.
Da ich derzeit keine Domain von extern habe, die auf DynDNS zeigt bzw. auf meine dynamische IP von meinem DSL und ich dafür noch keine FW-Freischaltung in meiner OPNSense gemacht habe, habe ich mich zeitweilig mit Einträgen in der hosts-Datei beholfen (Domain .int).
Traefik läuft und es kommen keine Fehlermeldungen, außer von ACME, weil er nicht registrieren kann, aber das ignoriere ich zeitweilig.

Nextcloud und MariaDB starten, allerdings bringt MariaDB ein paar interessante Fehlermeldungen oder Warnmeldungen, die ich auch nach Googlen und einigem herumprobieren nur teilweise lösen kann.

nextcloud-db     | 2020-01-11 10:17:49 0 [Warning] You need to use --log-bin to make --binlog-format work.
nextcloud-db     | 2020-01-11 10:17:49 0 [Warning] 'user' entry 'root@0b1a4ea85fec' ignored in --skip-name-resolve mode.
nextcloud-db     | 2020-01-11 10:17:49 0 [Warning] 'user' entry '@0b1a4ea85fec' ignored in --skip-name-resolve mode.
nextcloud-db     | 2020-01-11 10:17:49 0 [Warning] 'proxies_priv' entry '@% root@0b1a4ea85fec' ignored in --skip-name-resolve mode.

im Nextcloud WebUI erhalte ich nach Eingabe aller Daten diese Fehlermeldung:
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away

im Log finde ich dann das:

2020-01-11 10:23:42 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '192.168.16.3' (This connection closed normally without authentication)

Nach etlichen Stunden des Ausprobierens komme ich hier nun nicht mehr weiter.

Die Warnung zu --binlog-format bekomme ich mit --log-bin=ROW weg... (da stimmt selbst die "Vorgabe" von nextcloud nicht), aber die Meldung mit den Usern und --skip-name-resolve mode lässt mich verzweifeln.

Hat jmd. einen Tipp? Danke

Gruß
Markus

**Comment by cbirkenbeul** [comment]
Hallo Markus,
ich habe festgestellt, dass man den DB Container am besten erst ein mal starten muss und laufen lassen bis er sich initialisiert hat. Ich mache das immer mit einem "docker-compose up {containername}". MariaDB und MySQL zeigen dir dann nach einigen Sekunden im Log "ready for connections" oder so ähnlich. Anschließend breche ich den Container ab und starte neu.
Probier es doch mal bitte so und geb mir bescheid. Danke.

**Comment by MarkusLoyen** [comment]
Hallo Christian,
es scheint ein Netzwerkproblem zu sein, da auch der Wordpress Container keine Verbindung zur MariaDB aufbauen kann.
Deiner Anweisung bin ich gefolgt, aber das System ist innerhalb sehr kurzer Zeit "ready for connections".

**Comment by cbirkenbeul** [comment]
Was nimmst du denn als Hostname für die Datenbank? Es müsste "nextcloud-db" sein, weil so der Container heißt.

**Comment by MarkusLoyen** [comment]
![image](https://user-images.githubusercontent.com/58221933/72688518-57616800-3b08-11ea-946d-a0ac8ec28b66.png)
![image](https://user-images.githubusercontent.com/58221933/72688530-73650980-3b08-11ea-8440-8229fd99560e.png)

**Comment by MarkusLoyen** [comment]
nextcloud/docker.compose.yaml

---
version: '3.3'

services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    restart: always
    volumes:
      - /var/docker/nextcloud/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=*****
      - MYSQL_PASSWORD=*****
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - traefik_proxy
      - default

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    volumes:
      - /var/docker/nextcloud/app:/var/www/html
    links:
      - nextcloud-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.int`)" #Domain anpassen
      - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.int`)" #Domain anpassen
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

**Comment by MarkusLoyen** [comment]
root@debiantest2019:~/docker-homelab/nextcloud# docker-compose logs nextcloud-db
Attaching to nextcloud-db
nextcloud-db     | 2020-01-19 21:05:29+01:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.11+maria~bionic started.
nextcloud-db     | 2020-01-19 21:05:30+01:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
nextcloud-db     | 2020-01-19 21:05:30+01:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.11+maria~bionic started.
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] mysqld (mysqld 10.4.11-MariaDB-1:10.4.11+maria~bionic-log) starting as process 1 ...
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Using Linux native AIO
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Uses event mutexes
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Number of pools: 1
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Using generic crc32 instructions
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: Completed initialization of buffer pool
nextcloud-db     | 2020-01-19 21:05:31 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: Creating shared tablespace for temporary tables
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: Waiting for purge to start
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: 10.4.11 started; log sequence number 487733; transaction id 798
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] Plugin 'FEEDBACK' is disabled.
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] InnoDB: Buffer pool(s) load completed at 200119 21:05:32
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] Server socket created on IP: '::'.
nextcloud-db     | 2020-01-19 21:05:32 0 [Warning] 'user' entry 'root@9393a98583b7' ignored in --skip-name-resolve mode.
nextcloud-db     | 2020-01-19 21:05:32 0 [Warning] 'user' entry '@9393a98583b7' ignored in --skip-name-resolve mode.
nextcloud-db     | 2020-01-19 21:05:32 0 [Warning] 'proxies_priv' entry '@% root@9393a98583b7' ignored in --skip-name-resolve mode.
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] Reading of all Master_info entries succeeded
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] Added new Master_info '' to hash table
nextcloud-db     | 2020-01-19 21:05:32 0 [Note] mysqld: ready for connections.
nextcloud-db     | Version: '10.4.11-MariaDB-1:10.4.11+maria~bionic-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
nextcloud-db     | 2020-01-19 21:07:21 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.27.0.3' (This connection closed normally without authentication)
nextcloud-db     | 2020-01-19 21:07:44 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.27.0.3' (This connection closed normally without authentication)
nextcloud-db     | 2020-01-19 22:09:52 11 [Warning] Aborted connection 11 to db: 'unconnected' user: 'unauthenticated' host: '172.27.0.3' (This connection closed normally without authentication)
root@debiantest2019:~/docker-homelab/nextcloud#

**Comment by cbirkenbeul** [comment]
Ich habe es jetzt mal nachgestellt. Es scheint ein schon länger bestehendes Problem mit dem Nextcloud Container zu geben. Wenn die Container hoch gefahren sind, warte mal ca. 3- 5 Minuten ab mit dem Einrichten. Dann funktioniert das Setup. Wenn man das Problem googelt findet man das das wohl häufiger auftritt.

**Comment by MarkusLoyen** [comment]
15 min. gewartet und dann ging es... WTF..
DANKE für den Support, aber unglaublich
