### ISSUE TITLE
recipes 2. Instanz hochziehen

### ISSUE THREAD

**Issue by jboykov** [cbirkenbeul/docker-homelab#118]
Servus, kann man eine 2. Instanz von recipes laufen lassen? 
habe es versucht und die notwendigen Container umbenannt. Möchte die Kochrezepte von den Weinrezepten trennen.

Danke

**Comment by cbirkenbeul** [comment]
Hi,
ja kann man im Regelfall. Du musst nur aufpassen dass du wirklich alles sauber umbenennst in der 2. Instanz. Ich vergesse da gern mal ne Kleinigkeit wenn ich das mache.

Sobald du die Compose Datei startest bekommst du aber wohl ne Warnung angezeigt die du ignorieren kannst.
