### ISSUE TITLE
Probleme mit Traefik und anderen Containern

### ISSUE THREAD

**Issue by DeCeReH** [cbirkenbeul/docker-homelab#12]
Nach dem ich die docker-compose.yml Datei sowie die traefik.toml angepasst habe, funktioniert gar nichts mehr. Weder Wordpress, noch Nextcloud oder Portainer. Fehlermeldung im Browser "404 page not found". Hab ich noch was vergessen?

**Comment by cbirkenbeul** [comment]
Heißt bevor du es angepasst hast, funktionierte es? Was sagen die Logs? Die Informationen sind etwas spärlich um dir zielgerichtet weiterhelfen zu können.

**Comment by totti2** [comment]
Hallo zusammen,

ähnliches Problem: 404 page not found

Was ich erreichen will
---------------------------------
Traefik per Docker installieren
Traefik-Dashboard über traefik.domain.de verfügbar machen
Passwortschutz aktivieren

Was ich getan habe
-------------------------
docker network create traefik_proxy
chmod 600 acme.json
docker-compose.yaml - uncomment labels, korrigieren der domain und setzen des password
traefik.toml - setzen der mailadresse
docker-compose up -d

Was passiert ist
-------
404 für traefik.domain.de
certificate mismatch in ssllabs.com
ausgestellt für c131(...).08(...).traefik.default statt traefik.domain.de
cat amce.json = leer

docker logs traefik
```
time="2020-03-29T15:39:52+02:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2020-03-29T15:39:52+02:00" level=info msg="Traefik version 2.2.0 built on 2020-03-25T17:32:57Z"
time="2020-03-29T15:39:52+02:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-03-29T15:39:52+02:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-03-29T15:39:52+02:00" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/etc/traefik/dynamic.yml\"}"
time="2020-03-29T15:39:52+02:00" level=info msg="Starting provider *acme.Provider {\"email\":\"mail@adress.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/etc/traefik/ACME/acme.json\",\"keyType\":\"RSA4096\",\"tlsChallenge\":{},\"ResolverName\":\"default\",\"store\":{},\"ChallengeStore\":{}}"
time="2020-03-29T15:39:52+02:00" level=info msg="Testing certificate renew..." providerName=default.acme
time="2020-03-29T15:39:52+02:00" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"traefik_proxy\",\"swarmModeRefreshSeconds\":15000000000}"
time="2020-03-29T15:39:52+02:00" level=info msg="Starting provider *traefik.Provider {}"
```

Was mal gesagt werden muss
----------------
Vielen Dank für das tolle Repo! Es stellt genau das bereit, was ich gesucht hatte!
