### ISSUE TITLE
Frage: Verschiedene Netzwerke für Traefik

### ISSUE THREAD

**Issue by lucbas** [cbirkenbeul/docker-homelab#14]
Hi Christian

Danke für dieses grossartige Repo, welches mich dabei unterstützt Traefik besser zu verstehen.

Kurze Frage:
Ich habe gesehen, dass du jeweils 2 Netzwerke "traefik_proxy" und "default" einsetzt. Könntest du erlären, was dies genau macht, bzw. was der Sinn dahinter ist?

Ist ein Netzwerk von Traefik abgeschirm und öffentlich nicht erreichbar und zum Schutz der Container vorhanden?

Ich würde gerne ähnlich, wie bei deinem Repo, Traefik als Reverse Proxy einsetzen und die Container in einem nicht-öffentlich-zugänglichen Netzwerk betreiben. Die Container haben in diesem separaten Netzwerk die Ports exposed, da die Ports gegenseitig für die Kommunikation benötigt werden. Requests von aussen leitet Traefik dann weiter an die Container.

Aktuell konnte ich Traefik und die Container zum laufen bringen, aber die Container-Ports (im docker-compose mit "ports" exposed) sind jeweils noch öffentlich zugänglich.

Grossen Danke und liebe Grüsse

**Comment by cbirkenbeul** [comment]
Hallo,
richtig, die verschiedenen Netzwerke sind zur Aufteilung und zur Absicherung gedacht. Zudem braucht Traefik nur sein Netzwerk überwachen um zu sehen ob da Container sind die veröffentlicht werden sollen.
Die Ports  der einzelnen Container nach außen aufmachen ist nicht notwendig, wenn du mit einem reverse proxy arbeitest, weil der sich um alles kümmert.

**Comment by lucbas** [comment]
Besten Dank für die Antwort! 😄

`traefik_proxy` ist demzufolge das Netzwerk, welches von Traefik gemanaged wird und den Traffic von aussen nimmt und an die Services weiterleitet.
Das `default` Netzwerk hat die anderen Services, welche von aussen nicht erreichbar sind, jedoch für die interne Kommunikation benötigt wird (zum Beispiel Wordpress <-> Datenbank), habe ich dies korrekt verstanden?

**Comment by cbirkenbeul** [comment]
Richtig. 
Wenn ich mal etwas mehr Zeit habe, werde ich es mal so umstellen, dass jeder Service auch sein eigenes Netzwerk bekommt. Stand jetzt könnte der Wordpress Container z. B. auch dem Plex Container kommunizieren. Ist nicht so schön, aber nicht unbedingt ein großes Sicherheitsrisiko.
