### ISSUE TITLE
Probleme mit Datenbank und Ilias-App

### ISSUE THREAD

**Issue by DeCeReH** [cbirkenbeul/docker-homelab#16]
Die Ilias-App kann sich nicht mit der Datenbank verbinden. Passwörter, DB-Username und DB-name stimmen aber.
![2020-01-22 11_37_47-Window](https://user-images.githubusercontent.com/27444494/72887307-ba6f1c80-3d0b-11ea-8a50-2f30ff7398a5.png)

**Comment by jboykov** [comment]
Die Passwörter der ILIAS_DB und MY_SQL sind verschieden (steht bei einem ilias)

**Comment by DeCeReH** [comment]
Das habe ich gesehen und geändert. Funktioniert trotzdem nicht.

**Comment by DeCeReH** [comment]
ilias-app kann sich mit der Datenbank verbinden.

**Comment by jboykov** [comment]
woran lag es?
