### ISSUE TITLE
Bookstack

### ISSUE THREAD

**Issue by jboykov** [cbirkenbeul/docker-homelab#17]
Sieht irgendwie komisch aus, oder? Zudem kann ich micht auch nicht anmelden.

![image](https://user-images.githubusercontent.com/57740862/72896473-23f92600-3d20-11ea-8417-7be14e84ae15.png)
![image](https://user-images.githubusercontent.com/57740862/72896503-32474200-3d20-11ea-98eb-2da652dc9367.png)
![image](https://user-images.githubusercontent.com/57740862/72896548-4e4ae380-3d20-11ea-897b-aee4d217024f.png)

Danke für deine Hilfe mit deinem Homelab, tolle Sache.

**Comment by marphDE** [comment]
Schließe mich an, sieht bei mir auch so aus.
Hoffe auf eine Lösung

**Comment by marphDE** [comment]
Wenn ich im Browser (Chrome) in den Einstellungen die Funktion zum Blocken von unsicheren Inhalten deaktiviere wird Bookstack normal angezeigt.
Allerdings ist dies ja nicht Standard.

Ich nutze ja die Konfiguration von Christian sowohl für Traefik als auch für Bookstack, lediglich die Domains habe ich angepasst. Bekomme auch angezeigt das dass Zertifikat "Nicht sicher" ist.

**Comment by cbirkenbeul** [comment]
So. Fehler ist behoben. Derjenige der den Container zur Verfügung stellt hat diesen leider nicht mehr geupdatet. Entsprechend habe ich den Container gewechselt. Anstatt mysql wird jetzt auch mariadb verwendet. 
Zudem muss noch eine environment Variable ergänzt werden. Ist aber alles in der Compose kommentiert.
