### ISSUE TITLE
Can´t access Website after setting Up docker

### ISSUE THREAD

**Issue by BiotTT** [cbirkenbeul/docker-homelab#183]
I have some issues with setting up an FreeScout-docker in my virtual machine runnig latest ubuntu. I need a ticketsystem for an schoolproject so it would be very nice if you could somehow help me. Attached are my docker-compose and the .env file. Also attached there is a screenshot of successfully starting the docker. When the docker is started, I just go in a browser and typ in https://localhost// or http://localhost/ or 10.10.0.201 (the ip-address from my virutal machine). I dont know why it doesnt work maybe because of my virtual machine? Please help me.

[attachments.zip](https://github.com/freescout-helpdesk/freescout/files/8424135/attachments.zip)
I asked the question allread in Freescout's github but there is still no answer so I hope you can help me here.
For all the Germans if you would answer in German it would be very nice.

**Comment by cbirkenbeul** [comment]
Hi,
i had a discord member a few days ago and he said the same. I had a look at it 2 days ago and the docker-compose-traefik.yaml works perfectly fine for me.
I guess you put all the values in the .env File?

**Comment by BiotTT** [comment]
Yeah thats right. Thanks For your answer because im also struggeling with the dokcer From the freescout GitHub. I will definetly try the traefik Version today. I will let you Know If it works
