### ISSUE TITLE
 Letsencrypt 

### ISSUE THREAD

**Issue by juliustech-create** [cbirkenbeul/docker-homelab#22]
Hallo,

Die Container laufen zwar, doch ich bekomme **ein fehlehaftes Zertifikat von letsencrypt ausgestellt.**
Es wird als unsicher definiert! 

Hoster ist "Strato".
 Kennt jemand hierfür eine Lösung ich habe die neue traefik Version verwendet.

**Comment by stereu** [comment]
Läuft Docker auf einem Server? VPS? Webhosting?
Mit Webhosting-Paketen kann es schonmal Probleme geben. Achte bei Server & VPS unbedingt auf korrekte Firewall-Einstellungen und korrekte DNS-Auflösung. Letztere kannst du zum Beispiel mit [mxtoolbox.com](mxtoolbox.com) testen.
Ich kann bestätigen, dass es sonst läuft.

**Comment by juliustech-create** [comment]
Das ganze läuft auf einem VPS. Ein extra Firewall ist nicht konfiguriert. Ich habe nur einen DNS Eintrag von meiner Server-IP auf meine Domain. 

In diesem Falle benötige ich auch keine Subdomains oder? 



> Läuft Docker auf einem Server? VPS? Webhosting?
> Mit Webhosting-Paketen kann es schonmal Probleme geben. Achte bei Server & VPS unbedingt auf korrekte Firewall-Einstellungen und korrekte DNS-Auflösung. Letztere kannst du zum Beispiel mit [mxtoolbox.com](mxtoolbox.com) testen.
> Ich kann bestätigen, dass es sonst läuft.

**Comment by juliustech-create** [comment]
Die Docker laufen auf einem VPS. Ich habe keine extra Firewall konfiguriert. Ebenfalls habe ich nur einen DNS Eintrag von meiner Server IP auf meine Domain.

> Läuft Docker auf einem Server? VPS? Webhosting?
> Mit Webhosting-Paketen kann es schonmal Probleme geben. Achte bei Server & VPS unbedingt auf korrekte Firewall-Einstellungen und korrekte DNS-Auflösung. Letztere kannst du zum Beispiel mit [mxtoolbox.com](mxtoolbox.com) testen.
> Ich kann bestätigen, dass es sonst läuft.
