### ISSUE TITLE
Nextcloud  auf einem VPS

### ISSUE THREAD

**Issue by jboykov** [cbirkenbeul/docker-homelab#26]
Habe einen VPS gemietet und darauf dein dein Homelab kopiert und entsprechend angepasst.

Habe folgendes Problem bei Nextcloud:
Bei den Sicherheits- & Einrichtungswarnungen habe ich folgende Meldung:
"Die Reverse-Proxy-Header-Konfiguration ist fehlerhaft oder Du greifst auf Nextcloud über einen vertrauenswürdigen Proxy zu. Ist dies nicht der Fall, dann besteht ein Sicherheitsproblem, das einem Angreifer erlaubt die IP-Adresse, die für Nextcloud sichtbar ist, auszuspähen. Weitere Informationen hierzu finde sich in der Dokumentation."

Habe folgende Schritte ausgeführt:

1. gehe zu:
 cd /var/docker/nextcloud/app/config/

2. finde die IP des Traefik Proxies heraus:
docker network inspect traefik_proxy --format='{{(index .IPAM.Config 0).Gateway}}'
-- Ergebnis war: 172.18.0.1

3. öffne die config.php:
nano config.php

4. ergänze folgende Inhalte (setze diese unternhalb ein) und passe diese an:
  array (
  'trust_proxies' => ['172.18.0.1'], # punkt 2
  'overwritehost' => 'traefik',      
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/nextcloud.subdomainURL',
  ),

zeigt mir aber weiterhin  diese Warnung an, trotz Versuch den Stack down und wieder up zu holen.

Ich hoffe die Infos helfen um das Problem zu lösen. 

Danke dir und weier so.

**Comment by cbirkenbeul** [comment]
Danke. Ich schaue es mir mal an. Ich hatte schon ein zwei mal geguckt ob ich es gefixt bekomme, aber immer kam was dazwischen. Kann ja eigentlich nicht so schwer sein.

**Comment by cbirkenbeul** [comment]
Ich habe jetzt diverses angepasst und getestet. Nun läuft (bei mir) Nextcloud ohne Sicherheitswarnung. Bitte beachte, dass diverse Dateien angepasst habe. 

https://github.com/cbirkenbeul/docker-homelab/commit/0d02cb556a2304fd9bc9cb48d998f45996575826

Gib mir bitte bescheid ob noch Fehler auftreten. Andernfalls schließe ich das Ticket in einer Woche.

**Comment by jboykov** [comment]
Super danke, jetzt ist das Schloss immer grün, nicht wie vorher das es bei Bildern etc. grau wurde.

Aber bei den Sicherheitswarnungnen ist immer noch die Meldung, siehe Bild. 
Schaue mir das an und würde mich melden, sobald ich eine Lösung habe.
![Unbenannt](https://user-images.githubusercontent.com/57740862/79430219-e592a080-7fc8-11ea-8d5e-3bb22f8bbd5d.PNG)

**Comment by cbirkenbeul** [comment]
Ah. Schau mal in meinem [Blogbeitrag](https://teqqy.de/nextcloud-docker-tutorial-step-by-step-zum-erfolg/). Da hab ich noch ein paar Anpassungen drin die ich nicht im Container direkt machen kann.

**Comment by jboykov** [comment]
Super passt, hatte schon 90% richtig. Den Rest habe ich aus deinem Block. Danke super.
