### ISSUE TITLE
Fehler in monitoring

### ISSUE THREAD

**Issue by azrarel783** [cbirkenbeul/docker-homelab#4]
Hi,
ich wollte mal dein Monitoring ausprobieren. Das funktioniert nur leider nicht, da bei mir grafana ständig neu startet. Wenn ich grafana einfach per "docker run" ausführe läuft es. Anscheinend ist wohl in der docker-compose.yaml ein Fehler?!
Bei mir hat er zb auch gemeldert, dass Version 3 falsch sei. Erst mit Version 2 konnten die Container gestartet werden.

**Comment by cbirkenbeul** [comment]
Sorry für die späte Antwort. Der Datenpfad für Grafana muss mittlerweile vorher angelegt und mit entsprechenden Rechten ausgestattet werden. Ich habe das in der Anleitung entsprechend hinterlegt.
