### ISSUE TITLE
Traefik 3 config does not have middleware secHeaders

### ISSUE THREAD

**Issue by hyagos-net** [cbirkenbeul/docker-homelab#405]
after the latest config update for traefik the middlware secHeaders does not exist anymore.

It can be fixed by changing this line in the docker-compose files of the used services(e.g. nextcloud, heimdall):

from
      - "traefik.http.routers._xxx_.middlewares=**secHeaders**@file"
to
      - "traefik.http.routers._xxx_.middlewares=**default**@file"

**Comment by cbirkenbeul** [comment]
Hi. Thanks. I totally forgot that after changing the traefik.yaml file. Its not fixed.
