### ISSUE TITLE
[Idee][Hilfe] rclone container in Verbindung mit Plex

### ISSUE THREAD

**Issue by Norrodar** [cbirkenbeul/docker-homelab#46]
Ich nutze [rclone](https://rclone.org/), um meine in GDrive gespeicherten Medien in Plex einzubinden. Hatte ich testweise trocken, ohne Docker, installiert.
Mein Ziel ist es, einen [rclone Container](https://hub.docker.com/r/rclone/rclone) zu basteln, auf den der Plex-Container zugreifen kann (auf den Medien-Ordner).
Es gibt unzählige Beispiele im Internet, sogar [Container mit Plex und rclone in einem](https://github.com/robinostlund/docker-plex-rclone). Diese werden aber nur von einer Person entwickelt, bleibt in der Entwicklung natürlich irgendwann stecken.

Es ergeben sich folgende Probleme:
1. Optimale Parameter für rclone unter Verwendung von Plex (Cache-Time, Cache-Größe, Limits an Zugriffen usw.)
2. UID und GID müssten für beide Container zwecks zugriff gleich sein (?)
3. Anbindung an Plex

Ich bin nicht sonderlich bewandert in Docker und bin mir gar nicht so sicher, ob es genügt, einfach ein rclone-Container dazu zu packen. **Daher bitte ich um Mithilfe! <3**
[In meinem Repo (Master)](https://github.com/Norrodar/docker-homelab/tree/master/rclone) habe ich zumindest schonmal das Gerüst gebaut, nach und nach kommt es dann wohl zusammen.

**Comment by dvogt23** [comment]
Wie wäre es, wenn du ein Verzeichnis in beide Container mountest? 🤔 Sollte funktionieren ...

**Comment by cbirkenbeul** [comment]
Ich würde auch eher eigenständige Container bevorzugen. So kann man sie unabhängig voneinander konfigurieren. Anschließend dann wie @dvogt23 schrieb, entsprechend in beiden Containern mounten. 

@Norrodar Gib mal bitte Feedback dazu, was dagegen sprechen könnte. Danke.

**Comment by Norrodar** [comment]
Dagegen spricht, dass der rclone-Container allgemeingültig ist, damit er für alle Anwendungen funktioniert.
Plex benötigt aber andere Parameter für rclone und Google Drive:
- Zur Umgehung des API-Hit-Limits (Plex ist sehr fleißig)
- Größe und Dauer des Caches (4Gb+ für 24h) wäre für andere Anwendungen ungeeignet.
- Dateiberechtigungen (hatte damit bisher immer Probleme)
