### ISSUE TITLE
Bitwarden Admin Page

### ISSUE THREAD

**Issue by Angelo131095** [cbirkenbeul/docker-homelab#48]
Hallo ich habe mir bitwarden_rs eingerichte und auch in der Docker compose die Variable ADMIN_TOKEN gesetzt.
 Aber wenn ich auf /admin zugreifen will kommt die Meldung das der Admin Token gesetzt werden muss.

Kann jemand helfen?

**Comment by dvogt23** [comment]
Bei mir funktioniert es:
```
environment:
  SIGNUPS_ALLOWED=false
  ADMIN_TOKEN=secrettoken
```

**Comment by Angelo131095** [comment]
Ok werde es nochmal testen

**Comment by Angelo131095** [comment]
kannst du mir mal dein Compose file schicken? bei mir startet es jetzt überhaupt nicht mehr, hatte es mal zum laufen gebracht aber versehentlich das Compose file gelöscht

**Comment by dvogt23** [comment]
Nimm die Beispiel compose Datei des Projekts und füg die Zeile mit Admintoken hinzu.

**Comment by Angelo131095** [comment]
ok klappt jetzt allerdings werde ich nach eingabe des Tokens auf der Admin Page zu localhost/admin und nicht zu meiner Domain geleitet

**Comment by Angelo131095** [comment]
hier mal mein compose File:
`version: '3'
services:
  bitwarden:
    image: bitwardenrs/server
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'
      ADMIN_TOKEN: 'secrettoken'
  caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - caddycerts:/root/.caddy
    ports:
      - 80:80
      - 443:443
    environment:
      ACME_AGREE: 'true'
      DOMAIN: 'domain.de'
      EMAIL: 'xxxx'

volumes:
  caddycerts:`
