### ISSUE TITLE
Pihole - Anleitung/Video?

### ISSUE THREAD

**Issue by fogx** [cbirkenbeul/docker-homelab#49]
Moin,

gibt es für die Pihole docker-compose eigentlich einen blogpost/video? Ich habe aktuell Pihole ohne docker laufen und habe es über das config tool eingerichtet. Bei den Einstellungen im docker-compose von dir bin ich mir nicht ganz sicher, was was ist. Besonders die ports, extra_hosts und labels von Traefik.
Würde sehr gerne Traefik vor Pihole schalten und die anderen tollen guides von dir ausprobieren!

**Comment by cbirkenbeul** [comment]
Ist in Planung. 👍
