### ISSUE TITLE
Multiple Doamins in Traefik

### ISSUE THREAD

**Issue by DeCeReH** [cbirkenbeul/docker-homelab#56]
Hallo,
ich möchte gerne mehrere Domains in Traefik hinzufügen und habe schon im Internet nach Anleitungen gesucht und auch ein paar gefunden. Leider musste ich feststellen, das hinterher der Traefik Proxy nicht mehr funktionierte. Sprich, die Anleitungen, die ich gefunden habe, sind mit der Traefik Config inkompatibel. Wäre es möglich, hier eine Anlaufstelle / Anleitung hinzuzufügen?

Vielen Dank schon mal im voraus. :)

**Comment by cbirkenbeul** [comment]
Du musst in den Labels einfach nur eine andere Domain eintragen. Ich betreibe Traefik mit ca. 6 verschiedenen Domänen in meiner public Infrastruktur.

**Comment by DeCeReH** [comment]
Mehr nicht? Das ist ja echt easy. 😊
