### ISSUE TITLE
Datenbankfehler bei Wordpress

### ISSUE THREAD

**Issue by DeCeReH** [cbirkenbeul/docker-homelab#7]
Wenn ich den Wordpress-Container starte und dann die Seite im Browser aufrufe, kommt die Meldung: "Error establishing a database connection". Irgendwo in der Config muss ein Fehler sein, nur finde ich nichts.

**Comment by cbirkenbeul** [comment]
Es war eine Kombination aus zwei Dingen die dazu geführt haben:
1. Habe ich den Datenbankcontainer einen falschen Namen verpasst
2. Benötigt MariaDB mittlerweile recht lange zum starten. Das habe ich in der Anleitung entsprechend angepasst.

**Comment by DeCeReH** [comment]
Ich hab es gemacht wie beschrieben. Der Fehler bleibt bestehen.
<img width="480" alt="2019-12-19 18_48_15-OpenSSH SSH client" src="https://user-images.githubusercontent.com/27444494/71196423-567eb180-2290-11ea-9531-61299eb17bd0.png">
