### ISSUE TITLE
Attachment bei Bitwarden kann nicht heruntergeladen werden

### ISSUE THREAD

**Issue by fuchsi3010** [cbirkenbeul/docker-homelab#76]
Ich betreibe den trafik und bitwarden_rs Container (Danke für die compose-Files!) auf einem VPS bei einem Hosting-Anbieter.

Ich kann Attachments zwar hochladen und löschen, nicht aber herunterladen.
Die Animation in Bitwarden dreht sich endlos, ohne dass etwas passiert.

Nach etwas googlen kam ich zum Resultat, eine "Download env" sei nicht richtig gesetzt.
Ich würde meinen Fix gerne hier einbringen, damit es für andere von Anfang an funktioniert.

**Comment by fuchsi3010** [comment]
Der Issue kann egtl. gleich wieder geschlossen werden. Wollte es nur hier haben, falls jemand mit dem Problem durch die Issues sucht. (Macht man das so? Ist mein erstes mal 'mitmachen' auf github...)

**Comment by abc2006** [comment]
Hab zwar erst ein bisschen rumgeklickt, aber Danke, dein Eintrag war der erste, den ich gefunden habe. 
In Kurz: in der config.json "localhost" durch den FQDN ersetzen ;)
