### ISSUE TITLE
Freescout - Fehler in der Compose-Datei / Traefik externes Routing (DuckDns)

### ISSUE THREAD

**Issue by mischolz70** [cbirkenbeul/docker-homelab#82]
In der Zeile 33 ist freescout mit einem "e" geschrieben:
- "traefik.http.services.frescout.loadbalancer.server.port=80"

Ich habe ein OMV mit Traefik, SSL über LetsEncrypt und Duckdns sowie Nextcloud nach Anleitung von Knillix installiert.

https://knilix.home.blog/traefik-nextcloud-ssl-komplettguide/

Ich habe versucht, die dort empfohlenen Einstellungen von Nextcloud auf die Traefik-Labels von Freescout zu übertragen, ich bekomme auch eine korrekte Anzeige in Traefik. Beim Aufruf über freescout.FREESCOUT_URL jedoch einen Bad Gateway (502).

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freescout.entrypoints=http"
      - "traefik.http.routers.freescout.rule=Host(`${FREESCOUT_URL}`)"
      - "traefik.http.routers.freescout.middlewares=https-redirect@file"
      - "traefik.http.routers.freescout-secure.entrypoints=https"
      - "traefik.http.routers.freescout-secure.rule=Host(`${FREESCOUT_URL}`)"
      - "traefik.http.routers.freescout-secure.middlewares=https-redirect@file"
      - "traefik.http.routers.freescout-secure.tls=true"
      - "traefik.http.routers.freescout-secure.tls.certresolver=lets-encr"
      - "traefik.http.services.freescout.loadbalancer.server.port=80"
      - "traefik.http.services.freescout.loadbalancer.server.scheme=https"
    networks:
      - traefik-net
      - default

networks:
  traefik-net:
    external:
      name: traefik-net
  default:
    driver: bridge

**Comment by mr-bolle** [comment]
Hi @mischolz70,

Ich kann den Fehler mit dem Traefik Label bestätigen. 


Wegen deinem Fehler, müsstest du dich an den Blog wenden, der Traefik Container ist anders konfiguriert als im docker-homelab (es führen mehrere Wege nach Rom 😉)

**Comment by mischolz70** [comment]
Hi, vielen Dank für die Antwort, ich werde mich an das andere Blog wenden.

VG Michael

**Comment by mr-bolle** [comment]
fixes #83

**Comment by mr-bolle** [comment]
close
