### ISSUE TITLE
Recipes Problem

### ISSUE THREAD

**Issue by Caaruzo** [cbirkenbeul/docker-homelab#87]
Hallo und Danke fürs teilen des docker-homelab :)

Ich habe ein kleines Problem mit recipes und hoffe du kannst mir da bitte weiterhelfen.
Ich habe das Ganze nun mit docker-compose eingerichtet und das läuft auch. Nur wenn ich die Container neu erstellen lasse, ist die ganze Tandoor-Recipes Konfiguration / Rezepte weg und das Setup wird neu aufgerufen. Woran könnte das liegen? Muss noch irgend etwas aus dem Container in ein Volume?

Gruß Caaruzo

**Comment by cbirkenbeul** [comment]
Hi,
sorry für die sehr späte Rückmeldung. Wenn ich das gerade richtig gesehen habe, ist der POSTGRES_HOST in der compose Datei falsch. 😔
Mit dem Fix https://github.com/cbirkenbeul/docker-homelab/commit/182a05bcd17ecb94bf86459a25f82abe958203a2 sollte das behoben sein.
