### ISSUE TITLE
Nach Update bleibt Datenbankfehler bestehen

### ISSUE THREAD

**Issue by DeCeReH** [cbirkenbeul/docker-homelab#9]
Ich hab es so gemacht, wie beschrieben, leider funktioniert es immer noch nicht. 
<img width="480" alt="71196423-567eb180-2290-11ea-9531-61299eb17bd0" src="https://user-images.githubusercontent.com/27444494/71206123-22ad8700-22a4-11ea-806c-1ff38ec80a16.png">

**Comment by cbirkenbeul** [comment]
Hast du mal alle Daten gelöscht und neu gestartet? Also mal ein "docker-compose rm" und die Dateien im Abgelegten Verzeichnis?

**Comment by DeCeReH** [comment]
Hab ich gemacht, Fehler bleibt trotzdem.

**Comment by cbirkenbeul** [comment]
Kannst du bitte noch mal alles löschen. Anschließend nur den Datenbank Container starten und mir die Ausgabe mal hier ran hängen? 
Hast du noch weitere Container auf dem Host laufen?

**Comment by DeCeReH** [comment]
Ich hab das Problem behoben, nachdem ich die wp-config.php angepasst und den Container noch mal neugestartet habe. Jetzt funktioniert WordPress. Danke für deine Bemühungen und für deinen schnellen Support.
